name: Use Herald

on:
  pull_request_target:
    types: [edited, opened, synchronize, reopened]

jobs:
  applyRules:
    name: apply herald rules
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: jnwng/github-app-installation-token-action@c54add4c02866dc41e106745ac6dcf5cdd6339e5 # v2
        with:
          appId: ${{ secrets.UHA_APP_ID }}
          installationId: ${{ secrets.UHA_INSTALLATION_ID }}
          privateKey: ${{ secrets.UHA_APP_PRIVATE_KEY }}
      - uses: actions/checkout@master
      - name: Install packages
        run: npm install
      - id: herald
        uses: ./
        with:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
          rulesLocation: herald_rules/*.json
          DEBUG: '*'
